In [1]:
import numpy as np
import pandas as pd

In [2]:
# two matrics
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [3]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.83195119 0.23897571 0.55152995 0.83240275]
 [0.08280486 0.85036127 0.45299201 0.88714155]
 [0.22495771 0.0238044  0.27251921 0.45358409]]


In [4]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 81 -33]
 [ 79 -39]]


In [5]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[81, -33], [79, -39]]


In [6]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

5.333333333333333


In [7]:
main_data = pd.read_csv("../input/mtcars/mtcars.csv")

In [8]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
